package com.gmail.alexei28.shortcut.algorithms.module3.hashmap;

import java.util.HashMap;
import java.util.Map;

/*
    389. Find the Difference [Easy]
    Source: https://leetcode.com/problems/find-the-difference/description/
    Паттерн "Частотный анализ" (HashMap).
    You are given two strings s and t.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.

    Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

    Example 2:
    Input: s = "", t = "y"
    Output: "y"

    Решение:
    1. Временная сложность (Time Complexity): O(N)
    2. Пространственная сложность (Space Complexity): O(1) или O(K)
*/
public class Task18 {
    public char findTheDifference(String s, String t) {
        Map<Character, Integer> map = new HashMap<>();
        for (char item : s.toCharArray()) {
            map.put(item, map.getOrDefault(item, 0) + 1);
        }
        char findChar = 0;
        for (char item : t.toCharArray()) {
            if (map.containsKey(item)) {
                int count = map.get(item);
                if  (count == 0) {
                    findChar = item;
                    return item;
                }
                map.put(item, --count);
            } else {
                return item;
            }
        }
        return findChar;
    }
}
